"""
CamCal for camera calibration
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['PinholeSplinedConfig', 'PinholeSplinedIntrinsicsParameters', 'add', 'calibrate_opencv', 'fine_tune_pinhole_splined', 'get_matching_spline_distortion_model', 'make_undistortion_maps_pinhole_splined', 'project_pinhole_splined_points']
class PinholeSplinedConfig:
    def __init__(self, image_width: typing.SupportsInt, image_height: typing.SupportsInt, fov_deg_x: typing.SupportsFloat, fov_deg_y: typing.SupportsFloat, num_knots_x: typing.SupportsInt, num_knots_y: typing.SupportsInt) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def fov_deg_x(self) -> float:
        ...
    @fov_deg_x.setter
    def fov_deg_x(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def fov_deg_y(self) -> float:
        ...
    @fov_deg_y.setter
    def fov_deg_y(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def image_height(self) -> int:
        ...
    @image_height.setter
    def image_height(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def image_width(self) -> int:
        ...
    @image_width.setter
    def image_width(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_knots_x(self) -> int:
        ...
    @num_knots_x.setter
    def num_knots_x(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def num_knots_y(self) -> int:
        ...
    @num_knots_y.setter
    def num_knots_y(self, arg0: typing.SupportsInt) -> None:
        ...
class PinholeSplinedIntrinsicsParameters:
    def __init__(self, k4: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], dx_grid: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], dy_grid: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def dx_grid(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    @dx_grid.setter
    def dx_grid(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
    @property
    def dy_grid(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    @dy_grid.setter
    def dy_grid(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
    @property
    def k4(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    @k4.setter
    def k4(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
def add(a: typing.SupportsInt, b: typing.SupportsInt) -> int:
    """
    Add two integers together - test
    """
def calibrate_opencv(intrinsics_initial_value: collections.abc.Sequence[typing.SupportsFloat], intrinsics_param_optimize_mask: collections.abc.Sequence[bool], cameras_from_world: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]], target_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]], detections: collections.abc.Sequence[tuple[collections.abc.Sequence[typing.SupportsInt], collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]]]]) -> dict:
    ...
def fine_tune_pinhole_splined(model_config: ..., intrinsics_parameters: ..., cameras_from_world: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[6, 1]"]], target_points: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[3, 1]"]], detections: collections.abc.Sequence[tuple[collections.abc.Sequence[typing.SupportsInt], collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64, "[2, 1]"]]]]) -> dict:
    ...
def get_matching_spline_distortion_model(opencv_distortion_params: collections.abc.Sequence[typing.SupportsFloat], model_config: ...) -> dict:
    ...
def make_undistortion_maps_pinhole_splined(model_config: PinholeSplinedConfig, intrinsics: PinholeSplinedIntrinsicsParameters, new_k4: typing.Annotated[numpy.typing.ArrayLike, numpy.float64] | None = None, new_image_size_wh: tuple[typing.SupportsInt, typing.SupportsInt] | None = None) -> tuple:
    ...
def project_pinhole_splined_points(model_config: ..., intrinsics: ..., points_in_camera: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> numpy.typing.NDArray[numpy.float64]:
    ...
